public final class MockExportAPI {
    private let mode: ServerAuthorizationMode
    private let serverSessions: [String: SessionSnapshot]

    public init(mode: ServerAuthorizationMode) {
        self.mode = mode
        self.serverSessions = [
            "lab-token-alice": SessionSnapshot(
                token: "lab-token-alice",
                userID: "alice",
                role: .analyst,
                isPremium: true
            ),
            "lab-token-bob": SessionSnapshot(
                token: "lab-token-bob",
                userID: "bob",
                role: .viewer,
                isPremium: false
            )
        ]
    }

    @inline(never)
    public func perform(_ request: ExportRequest) -> ExportResult {
        var trace = [
            "server.received token=\(request.bearerToken)",
            "server.requestedOwner=\(request.requestedOwnerID)",
            "server.clientClaims role=\(request.claimedRole.rawValue), premium=\(request.claimedPremium)"
        ]

        guard let serverSession = serverSessions[request.bearerToken] else {
            trace.append("server.denied unknown token")
            return ExportResult(
                outcome: .deniedByServer,
                reason: "Unknown session",
                trace: trace
            )
        }

        switch mode {
        case .secure:
            return authorizeSecurely(request, serverSession: serverSession, trace: trace)
        case .trustsClientClaims:
            return authorizeUsingClientClaims(request, trace: trace)
        }
    }

    @inline(never)
    private func authorizeSecurely(
        _ request: ExportRequest,
        serverSession: SessionSnapshot,
        trace: [String]
    ) -> ExportResult {
        var trace = trace

        guard serverSession.userID == request.requestedOwnerID else {
            trace.append("server.denied owner mismatch")
            return ExportResult(
                outcome: .deniedByServer,
                reason: "Authenticated user does not own the requested report",
                trace: trace
            )
        }

        guard serverSession.isPremium,
              serverSession.role == .analyst || serverSession.role == .administrator else {
            trace.append("server.denied authoritative entitlement")
            return ExportResult(
                outcome: .deniedByServer,
                reason: "Server-side entitlement denied",
                trace: trace
            )
        }

        trace.append("server.allowed authoritative session and ownership")
        return ExportResult(outcome: .allowed, reason: "Export generated", trace: trace)
    }

    @inline(never)
    private func authorizeUsingClientClaims(
        _ request: ExportRequest,
        trace: [String]
    ) -> ExportResult {
        var trace = trace

        guard request.claimedPremium,
              request.claimedRole == .analyst || request.claimedRole == .administrator else {
            trace.append("server.denied client claims")
            return ExportResult(
                outcome: .deniedByServer,
                reason: "Client claims denied",
                trace: trace
            )
        }

        trace.append("server.allowed untrusted client claims without ownership check")
        return ExportResult(
            outcome: .allowed,
            reason: "Export generated by vulnerable authorization mode",
            trace: trace
        )
    }
}
